server:
  port: 8080
spring:

  application:
    name: Test Application
    data:
      mongodb:
        host: localhost
        port: 27017
        database:
        username:
        password:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: 1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      request.timeout.ms: 60000



feedme:
  ip: 127.0.0.1
  port: 8282