version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 # eg: HOST_IP_ADDR=$(ipconfig getifaddr en0) docker-compose up
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "dev.betting:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper


  provider:
    image: tsgtechtest/provider:1.0.0
    ports:
      - "8181:8181"
      - "8282:8282"