server:
  port: 9090
spring:
  application:
    name: Producer Application
    data:
      mongodb:
        host: localhost
        port: 27017
        database:
        username:
        password:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      request.timeout.ms: 60000
feedme:
  ip: 127.0.0.1
  port: 8282